services:
  postgres:
    image: postgres:15-alpine
    container_name: jobboard_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: my_job_board
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - corehire_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.2
    container_name: jobboard_elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # Kept false for easy local dev setup
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - corehire_network

  redis:
    image: redis:7-alpine
    container_name: jobboard_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - corehire_network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: corehire_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
      DATABASE_URL: postgresql://postgres:password123@postgres:5432/my_job_board?schema=public
      REDIS_URL: redis://redis:6379
      ELASTICSEARCH_NODE: http://elasticsearch:9200
    depends_on:
      - postgres
      - elasticsearch
      - redis
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - corehire_network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: corehire_frontend
    restart: always
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://backend:3000
    depends_on:
      - backend
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - corehire_network

volumes:
  postgres_data:
  es_data:
  redis_data:

networks:
  corehire_network:
    driver: bridge